name: zcchat2_for_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ^3.11.0

dependencies:
  archive: ^4.0.9
  audioplayers: ^6.5.1
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  http: ^1.5.0
  open_filex: ^4.7.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.2.1
  url_launcher: ^6.3.1
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/turn-back.svg
    - assets/log-24.svg
    - assets/microphone-solid.svg
    - assets/bootstrap/character/assets/test/Tachie/default.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/default.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/举手-吃惊.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/举手-开心.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/举手-生气.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/举手-认真.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/伤心.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/侧身-兴奋.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/侧身-正常.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/侧身-高兴.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/充满干劲.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/兴奋.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/哭泣.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/失落.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/好奇.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/尴尬.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/惊呆.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/愤怒.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/担心.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/正常.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/生气.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/睡觉.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/自信.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/观望.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/认真.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/鄙视.png
    - assets/bootstrap/character/assets/亚托莉/Tachie/高兴.png
    - assets/bootstrap/character/assets/亚托莉/config.json
    - assets/bootstrap/plugin/anime/Basic Animation Package.json
